import React, { useState, useEffect } from "react";
import { apiFetch, relativeTime, C, S } from "../App";

// ── Types ────────────────────────────────────────────────────────────

interface ArtifactSessionSummary {
  sessionId: string;
  artifactCount: number;
  inputCount: number;
  outputCount: number;
  totalSize: string;
  totalSizeBytes: number;
  portalUrl: string;
  firstCreatedAt: number;
  lastCreatedAt: number;
  channelId: string | null;
  userId: string | null;
}

interface ArtifactDetail {
  id: string;
  direction: "input" | "output";
  filename: string;
  mimeType: string | null;
  sizeBytes: number | null;
  size: string | null;
  discordUrl: string | null;
  downloadUrl: string;
  createdAt: number;
}

// ── Helpers ──────────────────────────────────────────────────────────

function formatSize(bytes: number): string {
  if (bytes < 1024) return `${bytes} B`;
  if (bytes < 1024 * 1024) return `${(bytes / 1024).toFixed(1)} KB`;
  if (bytes < 1024 * 1024 * 1024)
    return `${(bytes / (1024 * 1024)).toFixed(1)} MB`;
  return `${(bytes / (1024 * 1024 * 1024)).toFixed(2)} GB`;
}

function getFileIcon(
  mimeType: string | null,
  filename: string
): string {
  if (!mimeType) {
    if (filename.match(/\.(png|jpe?g|gif|webp|svg|bmp|ico)$/i)) return "🖼️";
    if (filename.match(/\.pdf$/i)) return "📕";
    if (filename.match(/\.html?$/i)) return "🌐";
    if (filename.match(/\.(js|ts|py|rb|go|rs|java|c|cpp|sh)$/i)) return "💻";
    if (filename.match(/\.(csv|json|xml|yaml|yml)$/i)) return "📊";
    return "📄";
  }
  if (mimeType.startsWith("image/")) return "🖼️";
  if (mimeType === "application/pdf") return "📕";
  if (mimeType.startsWith("text/html")) return "🌐";
  if (mimeType.startsWith("text/")) return "📝";
  if (mimeType.startsWith("audio/")) return "🎵";
  if (mimeType.startsWith("video/")) return "🎬";
  return "📄";
}

// ── Session List View ────────────────────────────────────────────────

function SessionList({
  sessions,
  onSelect,
}: {
  sessions: ArtifactSessionSummary[];
  onSelect: (sessionId: string) => void;
}) {
  const totalArtifacts = sessions.reduce((s, x) => s + x.artifactCount, 0);
  const totalSize = sessions.reduce((s, x) => s + x.totalSizeBytes, 0);

  return (
    <div>
      <div style={{ ...S.card, display: "flex", gap: 24, alignItems: "center" }}>
        <div>
          <div style={{ fontSize: 24, fontWeight: 700, color: C.text }}>
            {sessions.length}
          </div>
          <div style={{ fontSize: 12, color: C.textDim }}>Sessions</div>
        </div>
        <div>
          <div style={{ fontSize: 24, fontWeight: 700, color: C.text }}>
            {totalArtifacts}
          </div>
          <div style={{ fontSize: 12, color: C.textDim }}>Artifacts</div>
        </div>
        <div>
          <div style={{ fontSize: 24, fontWeight: 700, color: C.text }}>
            {formatSize(totalSize)}
          </div>
          <div style={{ fontSize: 12, color: C.textDim }}>Total Size</div>
        </div>
      </div>

      <div style={S.card}>
        {sessions.length === 0 ? (
          <div style={{ color: C.textDim, textAlign: "center", padding: 32 }}>
            No artifacts yet. Files uploaded to or generated by the agent will
            appear here.
          </div>
        ) : (
          <table style={S.table}>
            <thead>
              <tr>
                <th style={S.th}>Session</th>
                <th style={S.th}>Artifacts</th>
                <th style={S.th}>Size</th>
                <th style={S.th}>Last Active</th>
                <th style={S.th}>Actions</th>
              </tr>
            </thead>
            <tbody>
              {sessions.map((s) => (
                <tr key={s.sessionId}>
                  <td style={S.td}>
                    <div style={{ fontWeight: 500, fontFamily: "monospace", fontSize: 12 }}>
                      {s.sessionId.slice(0, 12)}…
                    </div>
                    {s.channelId && (
                      <div style={{ fontSize: 11, color: C.textDim, marginTop: 2 }}>
                        ch:{s.channelId.slice(-6)}
                      </div>
                    )}
                  </td>
                  <td style={S.td}>
                    <div style={{ display: "flex", gap: 6 }}>
                      <span style={S.badge("#79c0ff")}>↓ {s.inputCount}</span>
                      <span style={S.badge("#7ee787")}>↑ {s.outputCount}</span>
                    </div>
                  </td>
                  <td style={{ ...S.td, color: C.textDim, fontSize: 13 }}>
                    {s.totalSize}
                  </td>
                  <td style={{ ...S.td, color: C.textDim, fontSize: 13 }}>
                    {relativeTime(s.lastCreatedAt)}
                  </td>
                  <td style={S.td}>
                    <div style={{ display: "flex", gap: 4 }}>
                      <button
                        style={S.btnSmall}
                        onClick={() => onSelect(s.sessionId)}
                      >
                        View
                      </button>
                      <a
                        href={s.portalUrl}
                        target="_blank"
                        rel="noopener noreferrer"
                        style={{
                          ...S.btnSmall,
                          textDecoration: "none",
                          display: "inline-flex",
                          alignItems: "center",
                        }}
                      >
                        Portal ↗
                      </a>
                    </div>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        )}
      </div>
    </div>
  );
}

// ── Session Detail View ──────────────────────────────────────────────

function SessionDetail({
  sessionId,
  onBack,
}: {
  sessionId: string;
  onBack: () => void;
}) {
  const [artifacts, setArtifacts] = useState<ArtifactDetail[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");

  useEffect(() => {
    setLoading(true);
    apiFetch<{ artifacts: ArtifactDetail[] }>(`/api/artifacts/${sessionId}`)
      .then((d) => {
        setArtifacts(d.artifacts);
        setLoading(false);
      })
      .catch((e) => {
        setError(e.message);
        setLoading(false);
      });
  }, [sessionId]);

  const inputs = artifacts.filter((a) => a.direction === "input");
  const outputs = artifacts.filter((a) => a.direction === "output");
  const totalSize = artifacts.reduce((s, a) => s + (a.sizeBytes || 0), 0);

  function renderSection(
    title: string,
    emoji: string,
    items: ArtifactDetail[]
  ) {
    if (items.length === 0) return null;
    return (
      <div style={{ ...S.card, marginBottom: 16 }}>
        <h3 style={{ ...S.h3, marginBottom: 12 }}>
          {emoji} {title}{" "}
          <span style={{ fontWeight: 400, color: C.textDim, fontSize: 13 }}>
            ({items.length})
          </span>
        </h3>
        <table style={S.table}>
          <thead>
            <tr>
              <th style={{ ...S.th, width: 32 }}></th>
              <th style={S.th}>File</th>
              <th style={S.th}>Size</th>
              <th style={S.th}>Date</th>
              <th style={S.th}>Actions</th>
            </tr>
          </thead>
          <tbody>
            {items.map((a) => (
              <tr key={a.id}>
                <td
                  style={{
                    ...S.td,
                    textAlign: "center",
                    fontSize: 18,
                    width: 32,
                  }}
                >
                  {getFileIcon(a.mimeType, a.filename)}
                </td>
                <td style={S.td}>
                  <div style={{ fontWeight: 500 }}>{a.filename}</div>
                  {a.mimeType && (
                    <div
                      style={{ fontSize: 11, color: C.textDim, marginTop: 2 }}
                    >
                      {a.mimeType}
                    </div>
                  )}
                </td>
                <td style={{ ...S.td, color: C.textDim, fontSize: 13, whiteSpace: "nowrap" }}>
                  {a.size || "—"}
                </td>
                <td style={{ ...S.td, color: C.textDim, fontSize: 13, whiteSpace: "nowrap" }}>
                  {relativeTime(a.createdAt)}
                </td>
                <td style={S.td}>
                  <div style={{ display: "flex", gap: 4 }}>
                    <a
                      href={a.downloadUrl}
                      style={{
                        ...S.btnSmall,
                        textDecoration: "none",
                        display: "inline-flex",
                        alignItems: "center",
                      }}
                    >
                      ⬇ Download
                    </a>
                    {a.discordUrl && (
                      <a
                        href={a.discordUrl}
                        target="_blank"
                        rel="noopener noreferrer"
                        style={{
                          ...S.btnSmall,
                          textDecoration: "none",
                          display: "inline-flex",
                          alignItems: "center",
                        }}
                      >
                        Discord ↗
                      </a>
                    )}
                  </div>
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>
    );
  }

  return (
    <div>
      <button
        style={{
          ...S.btn,
          marginBottom: 16,
          background: "transparent",
          border: `1px solid ${C.border}`,
        }}
        onClick={onBack}
      >
        ← Back to All Sessions
      </button>

      <div style={{ ...S.card, display: "flex", gap: 24, alignItems: "center" }}>
        <div>
          <div style={{ fontSize: 12, color: C.textDim }}>Session</div>
          <div
            style={{
              fontFamily: "monospace",
              fontSize: 13,
              color: C.text,
              marginTop: 2,
            }}
          >
            {sessionId.slice(0, 16)}…
          </div>
        </div>
        <div>
          <div style={{ fontSize: 20, fontWeight: 700, color: C.text }}>
            {artifacts.length}
          </div>
          <div style={{ fontSize: 12, color: C.textDim }}>Artifacts</div>
        </div>
        <div>
          <div style={{ fontSize: 20, fontWeight: 700, color: C.text }}>
            {formatSize(totalSize)}
          </div>
          <div style={{ fontSize: 12, color: C.textDim }}>Total Size</div>
        </div>
      </div>

      {loading && (
        <div style={{ color: C.textDim, padding: 24, textAlign: "center" }}>
          Loading…
        </div>
      )}

      {error && (
        <div style={{ ...S.card, color: C.error, fontSize: 13 }}>{error}</div>
      )}

      {!loading && artifacts.length === 0 && (
        <div style={{ ...S.card, color: C.textDim, textAlign: "center", padding: 32 }}>
          No artifacts in this session.
        </div>
      )}

      {renderSection("Inputs", "📥", inputs)}
      {renderSection("Outputs", "📤", outputs)}
    </div>
  );
}

// ── Main Artifacts Page ──────────────────────────────────────────────

export default function Artifacts() {
  const [sessions, setSessions] = useState<ArtifactSessionSummary[]>([]);
  const [selectedSession, setSelectedSession] = useState<string | null>(null);
  const [error, setError] = useState("");

  const load = () => {
    apiFetch<{ sessions: ArtifactSessionSummary[] }>("/api/artifacts")
      .then((d) => {
        setSessions(d.sessions);
        setError("");
      })
      .catch((e) => setError(e.message));
  };

  useEffect(() => {
    load();
  }, []);

  return (
    <div>
      <div
        style={{
          display: "flex",
          justifyContent: "space-between",
          alignItems: "center",
          marginBottom: 16,
        }}
      >
        <h2 style={{ ...S.h2, marginBottom: 0 }}>
          📎 Artifacts
        </h2>
        <div style={{ display: "flex", gap: 8 }}>
          <a
            href="/artifacts"
            target="_blank"
            rel="noopener noreferrer"
            style={{
              ...S.btn,
              textDecoration: "none",
              display: "inline-flex",
              alignItems: "center",
            }}
          >
            Open Portal ↗
          </a>
          <button style={S.btn} onClick={() => { setSelectedSession(null); load(); }}>
            Refresh
          </button>
        </div>
      </div>

      {error && (
        <div style={{ ...S.card, color: C.error, fontSize: 13 }}>{error}</div>
      )}

      {selectedSession ? (
        <SessionDetail
          sessionId={selectedSession}
          onBack={() => setSelectedSession(null)}
        />
      ) : (
        <SessionList sessions={sessions} onSelect={setSelectedSession} />
      )}
    </div>
  );
}
